pipeline{
        agent any
        stages{
            stage('stage1'){
                steps{
                   sh 'echo This is stage1 triggerd by ${user}'
                }

            }
            stage('stage2'){
                steps{
                   sh '''
                        echo "Hello from stage2"
                   '''
                }
            }
            stage('stage3'){
                    steps{
                            sh '''
                                    bash ${WORKSPACE}/linux/script.sh
                            '''
                    }
            }

        }

}
