pipeline{
        agent any

        stages{
                stage('build'){
                        steps{
                          sh 'echo "Build is successful on Build stage"'
                        }
                 }
                 stage('test'){
                        steps{
                          sh 'echo "Build is successful on test stage"'
                        }
                 }

                  stage('deploy'){
                        steps{
                          sh 'echo "Build is successful on deploy stage"'
                        }
                 }
          
        }

}
